#!/usr/bin/env bash
# feedback — a suggestion box at the bottom of the hub. The user types free text
# and submits; a loopback backend attaches the gate-verified owner and forwards
# {owner, text} to a configured external intake (which creates a tracking item and
# returns its URL). Served as a same-origin subpath under the hub.
#
#   browser --> hub (tailscale serve) --(identity)--> hub nginx
#     /feedback/api/  -> airlock-feedback backend 127.0.0.1:BACKEND (loopback)
#
# The suggestion box UI ships INSIDE the hub launcher (hub/index.html, between
# </main> and <footer>) — the orchestrator already copies it to the webroot — so
# this installer only writes the backend unit + nginx fragment. External intake is
# enabled only if [apps.feedback].intake_url + a token are configured. Config from
# airlock.toml. Honors AIRLOCK_DRY_RUN=1.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/install/lib.sh"

require_cmd python3

airlock_load feedback
BACKEND_PORT="${AIRLOCK_FEEDBACK_BACKEND_PORT:?}"
CONFD="${AIRLOCK_CONFD:-/etc/airlock/nginx}"
IDENTITY_HEADER="${AIRLOCK_IDENTITY_HEADER:?}"
BACKEND_PY="$ROOT/apps/feedback/backend/airlock-feedback.py"
UNIT_DIR="$HOME/.config/systemd/user"

# Pluggable delivery targets — intake and/or mail. None configured = the box
# degrades to "not configured" (stays hidden).
INTAKE_URL="$(airlock_config get apps.feedback.intake_url 2>/dev/null || true)"
TOKEN_ENV="$(airlock_config get apps.feedback.token_env 2>/dev/null || true)"
[ -n "$TOKEN_ENV" ] || TOKEN_ENV=AIRLOCK_FEEDBACK_TOKEN

# Mail target. The recipient is deployment config (never a default in this repo);
# the API key lives in the env var named by mail_key_env, via the EnvironmentFile.
MAIL_TO="$(airlock_config get apps.feedback.mail_to 2>/dev/null || true)"
MAIL_FROM="$(airlock_config get apps.feedback.mail_from 2>/dev/null || true)"
MAIL_API="$(airlock_config get apps.feedback.mail_api 2>/dev/null || true)"
MAIL_KEY_ENV="$(airlock_config get apps.feedback.mail_key_env 2>/dev/null || true)"
[ -n "$MAIL_KEY_ENV" ] || MAIL_KEY_ENV=RESEND_API_KEY

# --- 1. systemd user unit (loopback backend) ---
if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then
  log "[dry] write $UNIT_DIR/airlock-feedback.service (127.0.0.1:$BACKEND_PORT, intake=${INTAKE_URL:-<none>}, mail=${MAIL_TO:+configured})"
else
  install -d "$UNIT_DIR"
  cat >"$UNIT_DIR/airlock-feedback.service" <<UNIT
[Unit]
Description=airlock feedback — suggestion-box relay (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
# Optional secret (the intake token) — safe if the file is absent.
EnvironmentFile=-%h/.config/airlock-feedback.env
Environment=AIRLOCK_FEEDBACK_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_FEEDBACK_INTAKE_URL=${INTAKE_URL}
Environment=AIRLOCK_FEEDBACK_TOKEN_ENV=${TOKEN_ENV}
Environment=AIRLOCK_FEEDBACK_MAIL_TO=${MAIL_TO}
# Quoted: a display-name from-address ("Name <a@b>") contains spaces, and systemd
# would otherwise split it into two assignments.
Environment="AIRLOCK_FEEDBACK_MAIL_FROM=${MAIL_FROM}"
Environment=AIRLOCK_FEEDBACK_MAIL_API=${MAIL_API}
Environment=AIRLOCK_FEEDBACK_MAIL_KEY_ENV=${MAIL_KEY_ENV}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
fi
airlock_run systemctl --user daemon-reload
airlock_run systemctl --user enable airlock-feedback.service
airlock_run systemctl --user restart airlock-feedback.service

# --- 2. nginx subpath fragment (included inside the hub server = server-level gate) ---
# Config, not a system mutation — written unconditionally. The backend strips the
# /feedback/ prefix itself. No per-location guard: the hub server-level gate
# ($hub_ok) covers it. nginx runtime vars are escaped as \$ so the shell never
# expands them; the only shell substitution is the backend port.
frag="$CONFD/hub-locations.d/feedback.conf"
install -d "$CONFD/hub-locations.d"
cat >"$frag" <<EOF
# feedback subpath — generated by apps/feedback/install.sh
# API backend (the backend strips the /feedback/ prefix itself). The suggestion
# box UI is part of the hub launcher (served by the hub's static webroot).
location /feedback/api/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    add_header Cache-Control "no-cache" always;
}
EOF
log "wrote nginx fragment: $frag"

# NOTE: smoke runs from the orchestrator AFTER nginx reload (gate not live before).
log "feedback installed (owner: ${AIRLOCK_OWNER}; intake: ${INTAKE_URL:-<none>}; mail: ${MAIL_TO:+configured}${MAIL_TO:-<none>})"
