# shellcheck shell=bash
# apps/feedback/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each function
# body is a VERBATIM copy of the heredoc it replaces, proven byte-identical
# to the inline text by install/test-render-parity.sh before any write site
# moves (P1b).

# render_feedback_unit BACKEND_PORT IDENTITY_HEADER INTAKE_URL TOKEN_ENV MAIL_TO MAIL_FROM MAIL_API MAIL_KEY_ENV
render_feedback_unit() {
  local BACKEND_PORT="$1" IDENTITY_HEADER="$2" INTAKE_URL="$3" TOKEN_ENV="$4" \
        MAIL_TO="$5" MAIL_FROM="$6" MAIL_API="$7" MAIL_KEY_ENV="$8"
  local BACKEND_PY="$ROOT/apps/feedback/backend/airlock-feedback.py"
  cat <<UNIT
[Unit]
Description=airlock feedback — suggestion-box relay (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
# Optional secret (the intake token) — safe if the file is absent.
EnvironmentFile=-%h/.config/airlock-feedback.env
Environment=AIRLOCK_FEEDBACK_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_FEEDBACK_INTAKE_URL=${INTAKE_URL}
Environment=AIRLOCK_FEEDBACK_TOKEN_ENV=${TOKEN_ENV}
Environment=AIRLOCK_FEEDBACK_MAIL_TO=${MAIL_TO}
# Quoted: a display-name from-address ("Name <a@b>") contains spaces, and systemd
# would otherwise split it into two assignments.
Environment="AIRLOCK_FEEDBACK_MAIL_FROM=${MAIL_FROM}"
Environment=AIRLOCK_FEEDBACK_MAIL_API=${MAIL_API}
Environment=AIRLOCK_FEEDBACK_MAIL_KEY_ENV=${MAIL_KEY_ENV}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_feedback_nginx BACKEND_PORT
render_feedback_nginx() {
  local BACKEND_PORT="$1"
  cat <<EOF
# feedback subpath — generated by apps/feedback/install.sh
# API backend (the backend strips the /feedback/ prefix itself). The suggestion
# box UI is part of the hub launcher (served by the hub's static webroot).
location /feedback/api/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    add_header Cache-Control "no-cache" always;
}
EOF
}
