#!/usr/bin/env bash
# devterm — browser web terminal (ttyd) behind the Airlock owner gate.
#
#   browser --https--> tailscale serve :HTTPS --(identity)--> nginx owner-gate
#           --(owner only / else 403)--> ttyd 127.0.0.1:TTYD --> tmux (auto-resume)
#
# Config comes from airlock.toml ([apps.devterm]). Ports/owner via airlock-config.
# Honors AIRLOCK_DRY_RUN=1 (print system-mutating steps instead of running them).
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/install/lib.sh"
# shellcheck source=/dev/null
. "$ROOT/gate/nginx-lib.sh"

airlock_load devterm
TTYD_PORT="${AIRLOCK_DEVTERM_TTYD_PORT:?}"
GATE_PORT="${AIRLOCK_DEVTERM_GATE_PORT:?}"
HTTPS_PORT="${AIRLOCK_DEVTERM_HTTPS_PORT:?}"
PUBLIC_PORT="${AIRLOCK_DEVTERM_PUBLIC_PORT:?}"
CONFD="${AIRLOCK_CONFD:-/etc/airlock/nginx}"
TTYD_BIN="${TTYD_BIN:-$HOME/.local/bin/ttyd}"
DEVTERM_LANG="${AIRLOCK_DEVTERM_LANG:-C.UTF-8}"
FONT_SIZE="${AIRLOCK_DEVTERM_FONT_SIZE:-15}"

require_cmd tmux

# --- 1. provision ttyd (sha256-pinned) ---
provision_ttyd() {
  [ -x "$TTYD_BIN" ] && { log "ttyd present: $TTYD_BIN"; return; }
  local ver=1.7.7 asset sha
  case "$(uname -m)" in
    x86_64)  asset=ttyd.x86_64;  sha=8a217c968aba172e0dbf3f34447218dc015bc4d5e59bf51db2f2cd12b7be4f55 ;;
    aarch64) asset=ttyd.aarch64; sha='' ;;   # no pin for arm64 yet — downloads unverified
    *) die "ttyd: unsupported arch $(uname -m) — install manually (github.com/tsl0922/ttyd)" ;;
  esac
  local url="https://github.com/tsl0922/ttyd/releases/download/${ver}/${asset}"
  if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then log "[dry] download+verify ttyd ${ver} -> $TTYD_BIN"; return; fi
  local tmp; tmp="$(mktemp)"
  curl -fsSL --max-time 60 -o "$tmp" "$url" || { rm -f "$tmp"; die "ttyd download failed: $url"; }
  if [ -n "$sha" ]; then
    local got; got="$(sha256sum "$tmp" | cut -d' ' -f1)"
    [ "$got" = "$sha" ] || { rm -f "$tmp"; die "ttyd sha256 mismatch got=$got want=$sha"; }
    log "ttyd sha256 verified ($ver)"
  else
    log "warning: no sha256 pin for $(uname -m) — ttyd downloaded unverified"
  fi
  install -D -m755 "$tmp" "$TTYD_BIN"; rm -f "$tmp"
}
provision_ttyd

# --- 2. shell wrapper + ttyd systemd user unit (loopback only) ---
airlock_run install -D -m755 "$HERE/bin/devterm-shell" "$HOME/.local/bin/devterm-shell"

UNIT_DIR="$HOME/.config/systemd/user"
if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then
  log "[dry] write $UNIT_DIR/airlock-devterm.service (ttyd -i 127.0.0.1 -p $TTYD_PORT)"
else
  install -d "$UNIT_DIR"
  cat >"$UNIT_DIR/airlock-devterm.service" <<UNIT
[Unit]
Description=airlock devterm — ttyd web terminal (127.0.0.1:${TTYD_PORT})
After=network.target

[Service]
Environment=LANG=${DEVTERM_LANG}
Environment=LC_CTYPE=${DEVTERM_LANG}
# -a: pass ?arg= as the shell's session name; -W: writable; -P 2: fast dead-conn detect
ExecStart=${TTYD_BIN} -i 127.0.0.1 -p ${TTYD_PORT} -P 2 -W -a -t fontSize=${FONT_SIZE} %h/.local/bin/devterm-shell
# KillMode=process so a redeploy restarts ttyd without killing tmux sessions born in its cgroup
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
fi
airlock_run systemctl --user daemon-reload
airlock_run systemctl --user enable airlock-devterm.service
airlock_run systemctl --user restart airlock-devterm.service

# --- 3. nginx owner-gate fragment (proxies GATE_PORT -> ttyd; owner-only) ---
# Written unconditionally: it is config the renderer includes, not a system mutation.
frag="$CONFD/servers.d/devterm.conf"
install -d "$CONFD/servers.d"
{
  echo "# devterm owner gate — generated by apps/devterm/install.sh"
  emit_owner_gate "$GATE_PORT" "127.0.0.1:${TTYD_PORT}" owner_ok
} > "$frag"
log "wrote nginx fragment: $frag"

# --- 4. tailscale serve: expose HTTPS (secure context) + HTTP (convenience) -> gate ---
# HTTPS gives a secure context (clipboard, OSC52). Needs the FQDN cert Tailscale issues.
airlock_run sudo tailscale serve --bg --https="${HTTPS_PORT}" "http://127.0.0.1:${GATE_PORT}"
airlock_run sudo tailscale serve --bg --http="${PUBLIC_PORT}"  "http://127.0.0.1:${GATE_PORT}"

# NOTE: smoke runs from the orchestrator AFTER nginx is rendered + reloaded
# (the gate isn't live until then). See install/airlock-install.sh.
log "devterm installed (owner: ${AIRLOCK_OWNER})"
