# shellcheck shell=bash
# apps/devterm/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each unit
# function body is a VERBATIM copy of the heredoc it replaces, proven
# byte-identical to the inline text by install/test-render-parity.sh before
# any write site moves (P1b).
#
# The nginx fragment is not a heredoc in install.sh (it composes
# gate/nginx-lib.sh's emit_owner_gate + emit_https_redirect), so
# render_devterm_nginx is a thin wrapper around those calls — included for a
# single P1b write-site swap.

# render_devterm_unit_ttyd DEVTERM_LANG TTYD_PORT TTYD_BIN FONT_SIZE
render_devterm_unit_ttyd() {
  local DEVTERM_LANG="$1" TTYD_PORT="$2" TTYD_BIN="$3" FONT_SIZE="$4"
  cat <<UNIT
[Unit]
Description=airlock devterm — ttyd PTY backend (127.0.0.1:${TTYD_PORT})
After=network.target

[Service]
Environment=LANG=${DEVTERM_LANG}
Environment=LC_CTYPE=${DEVTERM_LANG}
# -a: pass ?arg= to the shell as its session name; -W: writable; -P 2: fast dead-conn detect
ExecStart=${TTYD_BIN} -i 127.0.0.1 -p ${TTYD_PORT} -P 2 -W -a -t fontSize=${FONT_SIZE} %h/.local/bin/devterm-shell
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
}

# render_devterm_unit_gate BACKEND_PORT gate_env PY GATE_PY
# gate_env is the pre-built multi-line "Environment=K=V\n..." block (built by
# install.sh's add_env helper — unchanged, still outside this library).
render_devterm_unit_gate() {
  local BACKEND_PORT="$1" gate_env="$2" PY="$3" GATE_PY="$4"
  cat <<UNIT
[Unit]
Description=airlock devterm-gate — custom client + API, proxies to ttyd (127.0.0.1:${BACKEND_PORT})
After=network.target airlock-devterm.service
Wants=airlock-devterm.service

[Service]
Type=simple
${gate_env}ExecStart=${PY} ${GATE_PY}
# KillMode=process, same reason as the ttyd unit: the gate starts a detached
# \`codex login --device-auth\` that must outlive a redeploy. setsid does not leave the
# cgroup, so the default (control-group) kills the pending login while the user is
# entering the code on their phone — and the old credential is already backed out.
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
}

# render_devterm_nginx GATE_PORT BACKEND_PORT REDIRECT_PORT CANON
render_devterm_nginx() {
  local GATE_PORT="$1" BACKEND_PORT="$2" REDIRECT_PORT="$3" CANON="$4"
  echo "# devterm owner gate — generated by apps/devterm/install.sh"
  emit_owner_gate "$GATE_PORT" "127.0.0.1:${BACKEND_PORT}" owner_ok
  echo "# devterm plaintext -> https redirect (nothing is served over http)"
  emit_https_redirect "$REDIRECT_PORT" "$CANON"
}
