# shellcheck shell=bash
# apps/markwand/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each function
# body is a VERBATIM copy of the heredoc it replaces, proven byte-identical
# to the inline text by install/test-render-parity.sh before any write site
# moves (P1b).

# render_markwand_unit_markserv CODE_ROOT MS_PORT MS_BIN UNIT_PATH
render_markwand_unit_markserv() {
  local CODE_ROOT="$1" MS_PORT="$2" MS_BIN="$3" UNIT_PATH="$4"
  cat <<UNIT
[Unit]
Description=airlock markserv — markdown viewer for ${CODE_ROOT} (127.0.0.1:${MS_PORT})
After=network.target

[Service]
Type=simple
WorkingDirectory=${CODE_ROOT}
# markserv runs through env node, so this PATH decides whether the unit starts at
# all. It was hardcoded here until 2026-08-07 with no entry for wherever node
# actually lives, and a box that followed this repo's own preflight fix (snap)
# crash-looped: env: node: No such file or directory. The installer derives it now
# — see airlock_cmd_dirs in install/lib.sh.
Environment=PATH=${UNIT_PATH}
# --livereloadport false: no chokidar watcher (avoids EACCES on symlinked trees)
ExecStart=${MS_BIN} --address 127.0.0.1 --port ${MS_PORT} --livereloadport false --browser false --silent ${CODE_ROOT}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_markwand_unit_filebrowser CODE_ROOT FB_PORT FB_BIN FB_DB
render_markwand_unit_filebrowser() {
  local CODE_ROOT="$1" FB_PORT="$2" FB_BIN="$3" FB_DB="$4"
  cat <<UNIT
[Unit]
Description=airlock filebrowser — zero-login editor for ${CODE_ROOT} (127.0.0.1:${FB_PORT})
After=network.target

[Service]
Type=simple
WorkingDirectory=%h/.config/filebrowser
ExecStart=${FB_BIN} --database ${FB_DB} --root ${CODE_ROOT} --address 127.0.0.1 --port ${FB_PORT} --followExternalSymlinks=false
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_markwand_nginx MS_PORT FB_PORT
render_markwand_nginx() {
  local MS_PORT="$1" FB_PORT="$2"
  echo "# markwand subpath — generated by apps/markwand/install.sh"
  sed -e "s/@@MS@@/${MS_PORT}/g" -e "s/@@FB@@/${FB_PORT}/g" <<'NGINX'
# These locations are included inside the hub server, which gates every request
# at the server level ($hub_ok) — so they are plain proxies, no per-location guard.
# filebrowser editor (baseURL=/markwand/edit) — longest prefix wins over /markwand/
location /markwand/edit/ {
    proxy_pass http://127.0.0.1:@@FB@@;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_read_timeout 86400s;
    proxy_set_header Accept-Encoding "";
    # save -> jump back to the markserv viewer (filebrowser has no custom.js hook)
    sub_filter '</body>' '<script src="/__mw/markwand-editor.js"></script></body>';
    sub_filter_once off;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

# split-pane multitype viewer = the default entry at exactly /markwand/ (static file).
# Served from the hub webroot's /__mw/ (root is inherited from the hub server block).
# `alias <file>` on a trailing-slash location makes nginx append index.html, so use
# try_files. This exact (=) match wins for the bare path; /markwand/<file> falls
# through to the markserv prefix proxy below (the .md render fallback).
location = /markwand/ {
    try_files /__mw/markwand-split.html =404;
    default_type text/html;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

# markserv viewer — strip the /markwand/ prefix, inject tokens + enhance + edit button
location /markwand/ {
    rewrite ^/markwand/(.*)$ /$1 break;
    proxy_pass http://127.0.0.1:@@MS@@;
    proxy_set_header Host $host;
    proxy_set_header Accept-Encoding "";
    sub_filter '</head>' '<link rel="stylesheet" href="/__mw/markwand-tokens.css"></head>';
    sub_filter '</body>' '<script src="/__mw/markwand-enhance.js"></script><script src="/__mw/edit-button.js"></script><script src="/airlock-return.js" data-mode="corner" defer></script></body>';
    sub_filter 'href="/'  'href="/markwand/';
    sub_filter_once off;
    # sub_filter_types defaults to text/html — leaving it implicit avoids a
    # "duplicate MIME type" warning at nginx -t.
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}
NGINX
}
