#!/usr/bin/env bash
# code-server — browser IDE (coder/code-server, MIT) behind the Airlock owner gate.
#
#   browser --https--> tailscale serve :https_port --(identity)--> nginx owner-gate
#           --(owner only / else 403)--> code-server 127.0.0.1:backend_port
#
# v1 runs a single instance. Config from airlock.toml ([apps.code-server]).
# Honors AIRLOCK_DRY_RUN=1.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/install/lib.sh"
# shellcheck source=/dev/null
. "$ROOT/gate/nginx-lib.sh"

airlock_load code-server
GATE_PORT="${AIRLOCK_CODE_SERVER_GATE_PORT:?}"
BACKEND_PORT="${AIRLOCK_CODE_SERVER_BACKEND_PORT:?}"
HTTPS_PORT="${AIRLOCK_CODE_SERVER_HTTPS_PORT:?}"
CONFD="${AIRLOCK_CONFD:-/etc/airlock/nginx}"

VER=4.128.0
SHA256=79ba26bf186e5268a22b7c17b30a5f288a16c37791f0b86c27859e8fef103188
ASSET="code-server-${VER}-linux-amd64"
BIN="$HOME/.local/bin/code-server"
LIB="$HOME/.local/lib/${ASSET}"

# --- 1. provision code-server (sha256-pinned; no piped installer) ---
provision_code_server() {
  if [ -x "$LIB/bin/code-server" ] && "$LIB/bin/code-server" --version 2>/dev/null | head -1 | grep -q "$VER"; then
    ln -sfn "$LIB/bin/code-server" "$BIN"; log "code-server $VER present"; return
  fi
  case "$(uname -m)" in x86_64) ;; *) die "code-server: unsupported arch $(uname -m)";; esac
  local url="https://github.com/coder/code-server/releases/download/v${VER}/${ASSET}.tar.gz"
  if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then log "[dry] download+verify code-server $VER -> $BIN"; return; fi
  local td; td="$(mktemp -d)"
  curl -fsSL --max-time 90 -o "$td/cs.tgz" "$url" || { rm -rf "$td"; die "code-server download failed"; }
  local got; got="$(sha256sum "$td/cs.tgz" | cut -d' ' -f1)"
  [ "$got" = "$SHA256" ] || { rm -rf "$td"; die "code-server sha256 mismatch got=$got want=$SHA256"; }
  install -d "$HOME/.local/lib"; rm -rf "$LIB"
  tar -xzf "$td/cs.tgz" -C "$HOME/.local/lib" || { rm -rf "$td"; die "code-server extract failed"; }
  ln -sfn "$LIB/bin/code-server" "$BIN"; rm -rf "$td"
  log "code-server sha256 verified ($VER)"
}
provision_code_server

# --- 2. config + systemd unit (single instance, loopback, auth none) ---
# auth none is safe ONLY because the sole external path is the identity gate and
# the backend binds loopback (see SECURITY.md).
if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then
  log "[dry] write ~/.config/code-server/config.yaml + airlock-code-server.service (127.0.0.1:$BACKEND_PORT)"
else
  install -d "$HOME/.config/code-server" "$HOME/.config/systemd/user" "$HOME/.local/share/airlock-code-server"
  cat >"$HOME/.config/code-server/config.yaml" <<YAML
auth: none
cert: false
disable-telemetry: true
disable-update-check: true
YAML
  cat >"$HOME/.config/systemd/user/airlock-code-server.service" <<UNIT
[Unit]
Description=airlock code-server — browser IDE (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
ExecStart=%h/.local/bin/code-server --bind-addr 127.0.0.1:${BACKEND_PORT} --user-data-dir %h/.local/share/airlock-code-server --auth none --disable-telemetry --disable-update-check
MemoryHigh=2G
MemoryMax=3G
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
fi
airlock_run systemctl --user daemon-reload
airlock_run systemctl --user enable airlock-code-server.service
airlock_run systemctl --user restart airlock-code-server.service

# --- 3. nginx owner-gate fragment ---
frag="$CONFD/servers.d/code-server.conf"
install -d "$CONFD/servers.d"
{
  echo "# code-server owner gate — generated by apps/code-server/install.sh"
  emit_owner_gate "$GATE_PORT" "127.0.0.1:${BACKEND_PORT}" owner_ok
} > "$frag"
log "wrote nginx fragment: $frag"

# --- 4. tailscale serve (https only — code-server wants a secure context) ---
airlock_run sudo tailscale serve --bg --https="${HTTPS_PORT}" "http://127.0.0.1:${GATE_PORT}"

# NOTE: smoke runs from the orchestrator AFTER nginx reload (gate not live before).
log "code-server installed (owner: ${AIRLOCK_OWNER})"
