# shellcheck shell=bash
# apps/code-server/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution: install.sh
# sources this and calls the functions; the body of each unit function is a
# VERBATIM copy of the heredoc it replaces (proven byte-identical to the
# inline text by install/test-render-parity.sh before any write site moves).
#
# The nginx fragment is not a heredoc in install.sh (it composes
# gate/nginx-lib.sh's emit_slot_gate), so render_code_server_nginx is a thin
# wrapper around that call — included for a single P1b write-site swap.

# render_code_server_unit_slot BACKEND_BASE SLOT_CASE SLOTS
render_code_server_unit_slot() {
  local BACKEND_BASE="$1" SLOT_CASE="$2" SLOTS="$3"
  cat <<UNIT
[Unit]
Description=airlock code-server slot %i — browser IDE engine
After=network.target

[Service]
Environment=AIRLOCK_CS_BACKEND_BASE=${BACKEND_BASE}
# Only slots 1..${SLOTS} are allowed — a rogue instance (out of range) is a clean skip.
ExecCondition=/bin/sh -c 'case %i in ${SLOT_CASE}) exit 0;; *) exit 1;; esac'
ExecStart=%h/.local/bin/airlock-code-server-slot %i
MemoryHigh=2G
MemoryMax=3G
TasksMax=2048
LimitNOFILE=1048576
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
}

# render_code_server_unit_manager MANAGER_PORT SLOTS BACKEND_PORT AIRLOCK_OWNER AIRLOCK_IDENTITY_HEADER
render_code_server_unit_manager() {
  local MANAGER_PORT="$1" SLOTS="$2" BACKEND_PORT="$3" AIRLOCK_OWNER="$4" AIRLOCK_IDENTITY_HEADER="$5"
  cat <<UNIT
[Unit]
Description=airlock code-server slot manager API (127.0.0.1:${MANAGER_PORT})
# NOT After=default.target — same WantedBy=default.target ordering-cycle
# anti-pattern fixed in apps/paseo/render.sh; see that comment for the exact
# boot-log signature this produces. network.target matches
# airlock-code-server@.service just below and every other app unit here.
After=network.target

[Service]
Type=simple
Environment=AIRLOCK_CODE_SERVER_MANAGER_HOST=127.0.0.1
Environment=AIRLOCK_CODE_SERVER_MANAGER_PORT=${MANAGER_PORT}
Environment=AIRLOCK_CODE_SERVER_SLOTS=${SLOTS}
Environment=AIRLOCK_CODE_SERVER_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_CODE_SERVER_ALLOW=${AIRLOCK_OWNER}
Environment=AIRLOCK_IDENTITY_HEADER=${AIRLOCK_IDENTITY_HEADER}
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStart=%h/.local/bin/airlock-code-server-manager
Restart=on-failure
RestartSec=2
MemoryHigh=128M
MemoryMax=256M
TasksMax=128
NoNewPrivileges=yes

[Install]
WantedBy=default.target
UNIT
}

# render_code_server_nginx GATE_PORT BACKEND_PORT SLOTS MANAGER_PORT SHELL_DIR WEBROOT
# Requires AIRLOCK_IDENTITY_HEADER in the environment (emit_slot_gate reads it).
render_code_server_nginx() {
  local GATE_PORT="$1" BACKEND_PORT="$2" SLOTS="$3" MANAGER_PORT="$4" SHELL_DIR="$5" WEBROOT="$6"
  echo "# code-server slot gate — generated by apps/code-server/install.sh"
  emit_slot_gate "$GATE_PORT" "$BACKEND_PORT" "$SLOTS" "$MANAGER_PORT" owner_ok \
    "$SHELL_DIR" shell.html "$WEBROOT/assets/airlock-return.js"
}
