# shellcheck shell=bash
# apps/fileview/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each function
# body is a VERBATIM copy of the heredoc it replaces, proven byte-identical
# to the inline text by install/test-render-parity.sh before any write site
# moves (P1b).

# render_fileview_unit_filebrowser FB_PORT FB_BIN FB_DB
render_fileview_unit_filebrowser() {
  local FB_PORT="$1" FB_BIN="$2" FB_DB="$3"
  cat <<UNIT
[Unit]
Description=airlock filebrowser — file API for the viewer (127.0.0.1:${FB_PORT})
After=network.target

[Service]
Type=simple
# The state directory this app owns. It used to be %h/.config/filebrowser, which
# the installer stopped creating when the database moved — systemd fails CHDIR
# before ExecStart, so on a box with no leftover filebrowser directory the service
# never started at all. Boxes that had one hid the bug.
WorkingDirectory=%h/.config/airlock-fileview
# --root /: the tree is the filesystem. There is no configured boundary any more —
# what bounds this is the unix account the user service runs as (see SECURITY.md).
# --disableTypeDetectionByHeader: without it, building a directory listing OPENS
# every file whose MIME the extension does not settle, to read its first bytes.
# Measured with strace on the pinned binary — one listing of three extension-less
# files: 3 opens with detection on, 0 with this flag, 0 with it off in the stored
# config (so the flag does override the config). Under --root / that is a listing of
# /dev opening device nodes. The viewer decides how to render by extension anyway,
# so the server-side sniff buys nothing and costs that.
ExecStart=${FB_BIN} --database ${FB_DB} --root / --address 127.0.0.1 --port ${FB_PORT} --followExternalSymlinks=false --disableTypeDetectionByHeader
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_fileview_nginx FB_PORT [AUDIENCE]
render_fileview_nginx() {
  local FB_PORT="$1" AUDIENCE="${2:-owner}"
  # D7 / #249. The hub server gate is $hub_ok = owner AND collaborators, so being
  # included here is NOT enough to make an owner-only manifest true — the tile would
  # hide while fileview kept serving the whole filesystem to a collaborator, which is
  # the exact failure #249 fails closed against. fileview serves `/` read+write, so
  # the guard matters more here than anywhere: emit the explicit $owner_ok check on
  # every content location whenever the effective audience is not "shared", the same
  # way apps/learning/render.sh and apps/paseo/render.sh do. Unknown values fail closed.
  local GUARD=''
  # shellcheck disable=SC2016  # $owner_ok is an nginx variable, not a shell one — the
  # single quotes are load-bearing; expanding it would emit `if ( = 0)` and gate nothing.
  [ "$AUDIENCE" = "shared" ] || GUARD='if ($owner_ok = 0) { return 403; }'
  echo "# fileview subpath — generated by apps/fileview/install.sh"
  echo "# effective audience: ${AUDIENCE}"
  sed -e "s/@@FB@@/${FB_PORT}/g" -e "s|@@GUARD@@|${GUARD}|g" <<'NGINX'
# Included inside the hub server ($hub_ok = owner + collaborators). The per-location
# The per-location guard below narrows the content locations to the owner alone when this app's
# audience is not "shared", and is absent for "shared". filebrowser is headless: only
# its API is proxied. Its own web UI (which ships a settings page that could, among
# other things, turn on hideDotfiles) is not reachable, and nothing links to it.
# filebrowser is headless: only its API is proxied. Its own web UI (which ships a
# settings page that could, among other things, turn on hideDotfiles) is not
# reachable, and nothing links to it — the viewer is the only front end.
location /fileview/api/ {
    @@GUARD@@
    proxy_pass http://127.0.0.1:@@FB@@;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_read_timeout 86400s;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

# Static assets. They are already served by the hub's `location /` (try_files from
# the webroot); this location exists only to say how long they may be cached. Every
# URL the HTML points at carries ?v=<content hash>, so a changed file is a changed
# URL and a year is safe — that is the whole point of the stamping in install.sh.
# The HTML itself is NOT here: it is `location = /fileview/` below, no-store.
location /__fv/ {
    @@GUARD@@
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
}

# the viewer — one static document that renders markdown, code, JSON, CSV,
# notebooks, images, media and PDFs itself. Served from the hub webroot's /__fv/
# (root is inherited from the hub server block). `alias <file>` on a trailing-slash
# location makes nginx append index.html, so use try_files.
location = /fileview/ {
    @@GUARD@@
    try_files /__fv/viewer.html =404;
    default_type text/html;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

# Everything else under /fileview/ used to be markserv rendering a file at its own
# URL. Nothing serves those now, and without this they would fall through to the
# hub's SPA fallback and quietly answer with the hub's own index page. A file is
# addressed as /fileview/?path=<urlencoded>; deliberately no redirect from the old
# shape, because turning a raw path into a query string is exactly the encoding
# bug this app just finished removing.
location /fileview/ {
    return 404;
}
NGINX
}
