#!/usr/bin/env bash
# dev-monitor — per-box system/service/network/storage observability, served as a
# same-origin subpath under the hub (owner + collaborators). OBSERVABILITY-ONLY:
# the message/action console is deferred (its modules are not shipped in v1).
#
#   browser --> hub (tailscale serve) --(identity)--> hub nginx
#     /monitor/        -> dashboard UI (static, from the hub webroot)
#     /monitor/api/    -> airlock-dev-monitor backend 127.0.0.1:BACKEND (loopback)
#
# The backend binds loopback and strips the /monitor/ prefix itself. Config from
# airlock.toml ([apps.dev-monitor]). Honors AIRLOCK_DRY_RUN=1.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/install/lib.sh"

require_cmd python3

airlock_load dev-monitor
BACKEND_PORT="${AIRLOCK_DEV_MONITOR_BACKEND_PORT:?}"
MESSAGES="${AIRLOCK_DEV_MONITOR_MESSAGES:-false}"
CONFD="${AIRLOCK_CONFD:-/etc/airlock/nginx}"
WEBROOT="${AIRLOCK_WEBROOT:-/opt/airlock/hub}"
IDENTITY_HEADER="${AIRLOCK_IDENTITY_HEADER:?}"
BACKEND_PY="$ROOT/apps/dev-monitor/backend/airlock-dev-monitor.py"
UNIT_DIR="$HOME/.config/systemd/user"

# --- 1. systemd user unit (loopback backend) ---
if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then
  log "[dry] write $UNIT_DIR/airlock-dev-monitor.service (127.0.0.1:$BACKEND_PORT, messages=$MESSAGES)"
else
  install -d "$UNIT_DIR"
  cat >"$UNIT_DIR/airlock-dev-monitor.service" <<UNIT
[Unit]
Description=airlock dev-monitor — system observability (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
Environment=AIRLOCK_DEV_MONITOR_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_DEV_MONITOR_MESSAGES=${MESSAGES}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
fi
airlock_run systemctl --user daemon-reload
airlock_run systemctl --user enable airlock-dev-monitor.service
airlock_run systemctl --user restart airlock-dev-monitor.service

# --- 2. dashboard UI into the hub webroot (served by the hub's static location /) ---
if [ "${AIRLOCK_DRY_RUN:-0}" = 1 ]; then
  log "[dry] install dev-monitor.html -> $WEBROOT/monitor/index.html"
else
  install -d "$WEBROOT/monitor"
  install -m644 "$HERE/frontend/dev-monitor.html" "$WEBROOT/monitor/index.html"
fi

# --- 3. nginx subpath fragment (included inside the hub server = server-level gate) ---
# Config, not a system mutation — written unconditionally. nginx runtime vars are
# escaped as \$ so the shell never expands them; the only shell substitutions are
# the backend port and the same-box origin regex below. No per-location guard: the
# hub server-level gate ($hub_ok) covers it.
frag="$CONFD/hub-locations.d/dev-monitor.conf"
install -d "$CONFD/hub-locations.d"

# The unread badge (hub/assets/airlock-return.js) polls owner/messages/preview
# cross-origin from the separate-port tools (devterm/code-server/orca/paseo — same
# box, different ports). Build a regex matching ONLY this box's tailnet origins
# (host + any port) so the API can reflect the request Origin without ever using
# "*". If the FQDN can't be resolved, skip the echo (the badge just stays hidden
# cross-origin, no worse than before) rather than failing the install.
cors_lines=""
if fqdn="$(ts_fqdn 2>/dev/null)"; then
  short="${fqdn%%.*}"
  origin_re="^https?://(${fqdn//./\\.}|${short//./\\.})(:[0-9]+)?\$"
  cors_lines="$(cat <<CORS
    # Same-box unread-badge CORS: reflect the Origin only for this box's tailnet
    # host on any port; never "*" (which would let any site the owner happens to
    # visit read their message previews). Simple GET, no credentials -> no
    # preflight. When \$mon_acao is empty nginx omits the header (>=1.7.5), so
    # foreign origins stay blocked.
    set \$mon_acao "";
    if (\$http_origin ~* "${origin_re}") { set \$mon_acao \$http_origin; }
    add_header Access-Control-Allow-Origin \$mon_acao always;
    add_header Vary Origin always;
CORS
)"
else
  log "WARN: tailnet FQDN unresolved — unread-badge CORS echo skipped (badge hidden on separate-port tools)"
fi

cat >"$frag" <<EOF
# dev-monitor subpath — generated by apps/dev-monitor/install.sh
# API backend (the backend strips the /monitor/ prefix itself). The UI at
# /monitor/ is served by the hub's static webroot (WEBROOT/monitor/index.html).
location /monitor/api/ {
${cors_lines}
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    add_header Cache-Control "no-cache" always;
}
EOF
log "wrote nginx fragment: $frag"

# NOTE: smoke runs from the orchestrator AFTER nginx reload (gate not live before).
log "dev-monitor installed (owner: ${AIRLOCK_OWNER}; messages: ${MESSAGES})"
