# shellcheck shell=bash
# apps/dev-monitor/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each unit/
# fragment function body is a VERBATIM copy of the heredoc it replaces,
# proven byte-identical to the inline text by install/test-render-parity.sh
# before any write site moves (P1b).

# render_dev_monitor_unit BACKEND_PORT MESSAGES IDENTITY_HEADER cors_hosts DEVMON_ENV \
#                         [TOKEN_FRESHNESS TOKEN_WARN_HOURS TOKEN_STALE_HOURS]
# The token arguments default rather than being required: this function is called by
# install/test-systemd-ordering.sh and by fixtures written before the feature existed,
# and an unset positional under `set -u` would turn a missing argument into an unbound
# variable error rather than the feature simply being off.
render_dev_monitor_unit() {
  local BACKEND_PORT="$1" MESSAGES="$2" IDENTITY_HEADER="$3" cors_hosts="$4" DEVMON_ENV="$5"
  local TOKEN_FRESHNESS="${6:-false}" TOKEN_WARN_HOURS="${7:-24}" TOKEN_STALE_HOURS="${8:-24}"
  local RESTART_ENV="${9:-$HOME/.config/airlock/dev-monitor-restart.env}"
  local BACKEND_PY="$ROOT/apps/dev-monitor/backend/airlock-dev-monitor.py"
  cat <<UNIT
[Unit]
Description=airlock dev-monitor — system observability (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
Environment=AIRLOCK_DEV_MONITOR_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_DEV_MONITOR_MESSAGES=${MESSAGES}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_DEV_MONITOR_CORS_HOSTS=${cors_hosts}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS=${TOKEN_FRESHNESS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_WARN_HOURS=${TOKEN_WARN_HOURS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_STALE_HOURS=${TOKEN_STALE_HOURS}
# '-' = optional: with messages off the file is absent by design, and the backend
# then serves observability only. Secrets stay in this 0600 file, out of the unit.
EnvironmentFile=-${DEVMON_ENV}
EnvironmentFile=-${RESTART_ENV}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# Exact-match mutation location. The general observation location blanks these headers,
# so only this path can reach the restart gate with authenticated owner authority.
render_dev_monitor_restart_location() {
  local BACKEND_PORT="$1" hdr_var="$2" RESTART_SECRET="$3"
  cat <<NGXRESTART

location = /monitor/api/service/restart {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Devmon-Owner \$http_${hdr_var};
    proxy_set_header X-Devmon-Proxy-Secret "${RESTART_SECRET}";
    add_header Cache-Control "no-store" always;
}
NGXRESTART
}

# render_dev_monitor_owner_location BACKEND_PORT hdr_var DEVMON_SECRET
render_dev_monitor_owner_location() {
  local BACKEND_PORT="$1" hdr_var="$2" DEVMON_SECRET="$3"
  cat <<NGXOWNER

location /monitor/api/owner/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Devmon-Owner \$http_${hdr_var};
    proxy_set_header X-Devmon-Proxy-Secret "${DEVMON_SECRET}";
    add_header Cache-Control "no-store" always;
}
NGXOWNER
}

# render_dev_monitor_nginx BACKEND_PORT owner_location
render_dev_monitor_nginx() {
  local BACKEND_PORT="$1" owner_location="$2" restart_location="${3:-}"
  cat <<EOF
# dev-monitor subpath — generated by apps/dev-monitor/install.sh
# API backend (the backend strips the /monitor/ prefix itself). The UI at
# /monitor/ is served by the hub's static webroot (WEBROOT/monitor/index.html).
location /monitor/api/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    # An empty value means nginx does not pass the field at all, so a browser cannot
    # smuggle its own owner/secret in on the observability routes either.
    proxy_set_header X-Devmon-Owner "";
    proxy_set_header X-Devmon-Proxy-Secret "";
    add_header Cache-Control "no-cache" always;
}
${owner_location}
${restart_location}
EOF
}
