# shellcheck shell=bash
# apps/learning/render.sh — sourceable render library. Functions only, no
# top-level execution, matching apps/markwand/render.sh and apps/publish/render.sh.

# render_learning_unit_server LIBRARY PUBLISH_SHARE STATE_DIR PORT PROVIDER BACKEND_DIR UNIT_PATH
render_learning_unit_server() {
  local LIBRARY="$1" PUBLISH_SHARE="$2" STATE_DIR="$3" PORT="$4" PROVIDER="$5" BACKEND_DIR="$6"
  local UNIT_PATH="$7"
  cat <<UNIT
[Unit]
Description=airlock learning — study library (127.0.0.1:${PORT}), behind the hub owner gate
After=network.target

[Service]
Type=simple
# 🔴 The server needs the SAME PATH as the worker, and the reason is not obvious.
# It never spawns a CLI — but it PROBES for one when a link is pasted, so it can
# refuse right away instead of failing forty minutes later. A systemd user unit
# gets a bare PATH with no ~/.local/bin, so without this line the probe finds
# nothing on a box where both CLIs are installed and logged in, and every ingest
# request is refused. Measured 2026-08-22: that is exactly what happened.
Environment=PATH=${UNIT_PATH}
Environment="AIRLOCK_LEARNING_PORT=${PORT}"
Environment="AIRLOCK_LEARNING_LIBRARY=${LIBRARY}"
Environment="AIRLOCK_LEARNING_LISTING=${PROVIDER}"
Environment="AIRLOCK_LEARNING_SHARE_DIR=${PUBLISH_SHARE}"
Environment="AIRLOCK_LEARNING_STATE_DIR=${STATE_DIR}"
ExecStart=/usr/bin/python3 ${BACKEND_DIR}/airlock-learning.py
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_learning_unit_ingest LIBRARY STATE_DIR PROVIDER UNIT_PATH BACKEND_DIR UNSAFE_ENV
render_learning_unit_ingest() {
  local LIBRARY="$1" STATE_DIR="$2" PROVIDER="$3" UNIT_PATH="$4" BACKEND_DIR="$5"
  local UNSAFE_ENV="$6"
  cat <<UNIT
[Unit]
Description=airlock learning ingest worker — one link at a time
After=network.target

[Service]
Type=simple
# 🔴 The agent CLI picks its endpoint from the environment. If a cloud-provider
# variable survives into this unit the worker silently bills a different account
# than the owner's subscription, and nothing in the log says so. Unset them
# rather than trusting the session that started the manager to be clean.
#
# The list comes from the adapter (providers.py UNSAFE_BILLING_ENV), not from
# here. It used to be typed out twice and the two drifted — one of them was
# missing OPENAI_BASE_URL until somebody noticed by hand.
UnsetEnvironment=${UNSAFE_ENV}
Environment=HOME=%h
Environment=PATH=${UNIT_PATH}
Environment="AIRLOCK_LEARNING_LIBRARY=${LIBRARY}"
Environment="AIRLOCK_LEARNING_STATE_DIR=${STATE_DIR}"
Environment="AIRLOCK_LEARNING_AGENT=${PROVIDER}"
ExecStart=/usr/bin/python3 ${BACKEND_DIR}/ingest_runner.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
UNIT
}

# render_learning_nginx PORT
render_learning_nginx() {
  local PORT="$1"
  echo "# learning subpath — generated by apps/learning/install.sh"
  sed -e "s/@@PORT@@/${PORT}/g" <<'NGINX'
# The hub server gate is $hub_ok = owner AND collaborators. This app declares
# audience = owner only, so the server-level gate is NOT enough — an explicit
# $owner_ok check is what makes the manifest's claim true, the same way
# apps/paseo/render.sh:160 does it. Without it a collaborator could paste a link
# and have it ingested against the owner's own agent subscription.
location /learning/ {
    if ($owner_ok = 0) { return 403; }
    # 🔴 The trailing slash is load-bearing: without it nginx forwards the URI
    # unchanged and the backend — which routes / and /api/... and knows nothing
    # about a /learning prefix — 404s every request that came through the hub.
    # The deployed configuration this was ported from has it.
    proxy_pass http://127.0.0.1:@@PORT@@/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_read_timeout 300s;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}
NGINX
}
